# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'yuzhang6-Microsoft Azure internal Consumption(aafb27de-e728-4cb8-9e68-9afde1d1a849)'
    subscriptionId: 'aafb27de-e728-4cb8-9e68-9afde1d1a849'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'LogicAppStandard'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Drac-Zhang/DevOpsTest/blob/master/azure-devops-sample/template.json'
    csmParametersFileLink: 'https://github.com/Drac-Zhang/DevOpsTest/blob/master/azure-devops-sample/parameters.json'
    deploymentMode: 'Incremental'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'yuzhang6-Microsoft Azure internal Consumption(aafb27de-e728-4cb8-9e68-9afde1d1a849)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az functionapp config appsettings set --name DracLogicAppStandard --resource-group LogicAppStandard --settings "BLOB_CONNECTION_RUNTIMEURL=Test"
    addSpnToEnvironment: true
    useGlobalConfig: true
